version: "3.9"
services:
  api-debug:
    build: .
    command: npm run start:debug
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    ports:
      - "5000:5000"
      - "9229:9229"
